# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Dandy"
license = "GPLv3"
licenselink = "https://github.com/SpaceBudokan/Dandy/blob/master/LICENSE"
description = "A very minimalist blog theme for Hugo"
homepage = "https://spacebudokan.com/"
tags = ["hugo", "blog" , "minimalist"]
features = ["", ""]
min_version = 0.15

[author]
  name = "Space Budokan"
  homepage = "https://spacebudokan.com"
